#!/usr/bin/env python3
"""Regression checks for Arbiter's offline case-study create helper.

`integrations/arbiter/run_create.py` is the only place where a user's own words
become an Arbiter request body, so these checks pin its CLI contract — request
bodies, validation, review-option shapes — not any prose a harness prints around
it. Every case runs the helper as a separate process against temporary paths,
which also proves file-backed hostile text is serialized, never shell-evaluated.

Asserts:
  1. build-create emits an exact body, accepts all nine create platforms, and
     rejects the read-side `google_news` value;
  2. query, title, timestamp, and platform validation fails closed and never
     leaves a partial body behind;
  3. build-finalize honours --keep and --remove against the plan's original
     one-based numbering, and collapses duplicate phrases;
  4. plan-summary renders summary, sources, and fixed phrase numbers;
  5. plan-options emits one flat `options[]` array carrying `prompt`,
     `multi_select`, and stable `original_number` values;
  6. progress-summary renders both phases, flags a stalled run, and degrades
     predictably on incomplete payloads;
  7. shell metacharacters in every text input stay inert.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
HELPER = ROOT / "integrations" / "arbiter" / "run_create.py"
FIXTURES = ROOT / "tests" / "fixtures"

# Creation accepts nine platforms; google_news is a read-side posts filter only.
CREATE_PLATFORMS = (
    "youtube", "twitter", "bluesky", "reddit", "facebook",
    "linkedin", "fourchan", "instagram", "tiktok",
)
WINDOW = {"from": "2025-01-01T00:00:00Z", "to": "2025-01-15T00:00:00Z"}
ENTITIES = ["Acme Corp", "Researcher One"]
PLAN_HEAD = (
    "SUMMARY\nGrounded fixture summary.\n\nSOURCES\n"
    "1. Primary source - https://example.test/primary\n"
    "2. Untitled source - https://example.test/untitled\n\nSEARCH PHRASES\n"
)
PLAN_FOOT = "Phrase numbers are the plan's original positions and stay fixed.\n"
DISCLOSURE = (
    "Generated by Spotlight from Arbiter plan context; these are not search "
    "phrases returned by Arbiter."
)


def cmd(command: str, flags: dict[str, str]) -> subprocess.CompletedProcess[str]:
    """Invoke one subcommand without a shell; flag keys omit the leading ``--``."""
    argv = [command]
    for name, value in flags.items():
        argv += [f"--{name}", value]
    return subprocess.run(
        [sys.executable, str(HELPER), *argv],
        cwd=ROOT, capture_output=True, text=True, timeout=10, check=False,
    )


def write_json(path: Path, payload: Any) -> None:
    """Write one JSON input used by a subprocess case."""
    path.write_text(json.dumps(payload), encoding="utf-8")


def copy_plan(path: Path) -> Path:
    """Copy the shared search-plan fixture to a case-local path and return it."""
    shutil.copyfile(FIXTURES / "arbiter-create-plan.json", path)
    return path


def ok(proc: subprocess.CompletedProcess[str], expected_stdout: str) -> None:
    """Require a successful command with byte-exact stdout and no diagnostics."""
    assert proc.returncode == 0, (proc.stdout, proc.stderr)
    assert proc.stdout == expected_stdout, proc.stdout
    assert proc.stderr == "", proc.stderr


def rejected(proc: subprocess.CompletedProcess[str], message: str) -> None:
    """Require the validation-failure contract: exit 2, no stdout, a stated reason."""
    assert proc.returncode == 2, (proc.returncode, proc.stdout, proc.stderr)
    assert proc.stdout == "", proc.stdout
    assert proc.stderr.startswith("error: "), proc.stderr
    assert message in proc.stderr, proc.stderr


def exact_json(path: Path, expected: dict[str, Any]) -> None:
    """Require both the semantic value and its deterministic serialization."""
    raw = path.read_text(encoding="utf-8")
    assert json.loads(raw) == expected, raw
    assert raw == json.dumps(expected, indent=2, sort_keys=True) + "\n", raw


def create_flags(query: Path, out: Path, **extra: str) -> dict[str, str]:
    """Build a valid build-create flag map; ``extra`` keys use ``_`` for ``-``."""
    flags = {"query-file": str(query), "platforms": "reddit,youtube", **WINDOW, "out": str(out)}
    flags.update({name.replace("_", "-"): value for name, value in extra.items()})
    return flags


def check_create(tmp: Path) -> None:
    """Verify build-create's body, the platform allowlist, and input validation."""
    query, title, out = tmp / "query.txt", tmp / "title.txt", tmp / "create-body.json"
    query.write_text("Election narrative\nacross regions\n", encoding="utf-8")
    title.write_text('A "quoted" \\ title\n', encoding="utf-8")
    ok(cmd("build-create", create_flags(
        query, out, platforms="Reddit, youtube", to="2025-01-15T05:30:00+05:30",
        title_file=str(title))), f"wrote {out}\n")
    exact_json(out, {
        "search_query": "Election narrative\nacross regions",
        "platforms": ["reddit", "youtube"],
        "date_range": {"from": "2025-01-01T00:00:00Z", "to": "2025-01-15T05:30:00+05:30"},
        "title": 'A "quoted" \\ title',
    })
    # All nine create platforms are accepted together and keep caller order.
    query.write_text("valid query", encoding="utf-8")
    every = tmp / "all-platforms.json"
    ok(cmd("build-create", create_flags(query, every, platforms=",".join(CREATE_PLATFORMS))),
       f"wrote {every}\n")
    assert json.loads(every.read_text(encoding="utf-8"))["platforms"] == list(CREATE_PLATFORMS)

    out.unlink()
    query.write_text("  \n", encoding="utf-8")
    rejected(cmd("build-create", create_flags(query, out)), "query must contain 1..500 characters")
    query.write_text("x" * 501, encoding="utf-8")
    rejected(cmd("build-create", create_flags(query, out)), "query must contain 1..500 characters")
    query.write_text("x" * 500, encoding="utf-8")
    assert cmd("build-create", create_flags(query, out)).returncode == 0, "500 is the cap"
    out.unlink()
    query.write_text("valid query", encoding="utf-8")
    long_title, absent = tmp / "long-title.txt", tmp / "absent.txt"
    long_title.write_text("x" * 201, encoding="utf-8")
    # google_news is a read-side posts filter and must never reach creation.
    for override, message in (
        ({"platforms": "reddit,google_news"}, "unsupported platform(s): google_news"),
        ({"platforms": "reddit,myspace"}, "unsupported platform(s): myspace"),
        ({"platforms": ",,"}, "platforms must contain at least one platform"),
        ({"platforms": "reddit,reddit"}, "platforms must not contain duplicates"),
        ({"from": "not-a-date"}, "from must be an ISO-8601 timestamp"),
        ({"from": "2025-01-01T00:00:00"}, "from must include a timezone"),
        ({"from": "2025-01-15T00:00:00Z"}, "from must be earlier than to"),
        ({"to": "2999-01-01T00:00:00Z"}, "to must not be in the future"),
        ({"title_file": str(long_title)}, "title must contain at most 200 characters"),
        ({"title_file": str(absent)}, "cannot read title file"),
        ({"query_file": str(absent)}, "cannot read query file"),
    ):
        rejected(cmd("build-create", create_flags(query, out, **override)), message)
    assert not out.exists(), "validation failures must not write a request body"


def check_finalize(tmp: Path) -> None:
    """Verify --keep and --remove selection semantics and phrase deduplication."""
    plan = copy_plan(tmp / "finalize-plan.json")
    additions = tmp / "added-phrases.txt"
    additions.write_text("alpha narrative\nnew phrase\n\n", encoding="utf-8")
    kept = tmp / "finalize-keep.json"
    ok(cmd("build-finalize", {"plan-file": str(plan), "keep": "3, 1",
                              "phrases-file": str(additions), "out": str(kept)}),
       f"wrote {kept}\n")
    # --keep honours the numbers as given, and the re-added "alpha narrative"
    # collapses into the kept phrase instead of appearing twice.
    exact_json(kept, {"search_phrases": ["gamma \\ path", "alpha narrative", "new phrase"],
                      "final_entities": ENTITIES})
    # --remove is the inverse: name what drops and everything else survives in
    # the plan's original order, so numbering cannot drift between rounds.
    dropped = tmp / "finalize-remove.json"
    ok(cmd("build-finalize", {"plan-file": str(plan), "remove": "2", "out": str(dropped)}),
       f"wrote {dropped}\n")
    exact_json(dropped, {"search_phrases": ["alpha narrative", "gamma \\ path"],
                         "final_entities": ENTITIES})

    bad = tmp / "finalize-reject.json"
    rejected(cmd("build-finalize", {"plan-file": str(plan), "remove": "1,2,3", "out": str(bad)}),
             "remove must leave at least one phrase")
    both = cmd("build-finalize",
               {"plan-file": str(plan), "keep": "1", "remove": "2", "out": str(bad)})
    assert both.returncode == 2 and "not allowed with argument" in both.stderr, both.stderr
    neither = cmd("build-finalize", {"plan-file": str(plan), "out": str(bad)})
    assert neither.returncode == 2 and "one of the arguments" in neither.stderr, neither.stderr
    assert not bad.exists(), "a rejected selection must not write a finalize body"


def check_plan_summary(tmp: Path) -> None:
    """Verify the review block, fixed numbering, and malformed-plan rejections."""
    plan, out = copy_plan(tmp / "summary-plan.json"), tmp / "summary-finalize.json"
    ok(cmd("plan-summary", {"plan-file": str(plan)}),
       PLAN_HEAD + " 1. alpha narrative\n 2. beta \"quoted\" phrase\n 3. gamma \\ path\n\n"
       "3 of 3 phrases kept.\n" + PLAN_FOOT)
    # Removal markers keep the ORIGINAL numbering, so numbers the reviewer has
    # already seen still identify the same phrases on the next round.
    ok(cmd("plan-summary", {"plan-file": str(plan), "removed": "2"}),
       PLAN_HEAD + " 1. alpha narrative\n 2. beta \"quoted\" phrase  [removed]\n"
       " 3. gamma \\ path\n\n2 of 3 phrases kept.\nRemoved: 2\n" + PLAN_FOOT)
    # Space-separated numbers are accepted the way a reviewer actually types them.
    spaced = cmd("plan-summary", {"plan-file": str(plan), "removed": "1 3"})
    assert spaced.returncode == 0, spaced.stderr
    assert "1 of 3 phrases kept." in spaced.stdout, spaced.stdout
    rejected(cmd("plan-summary", {"plan-file": str(plan), "removed": "9"}),
             "removed indexes must be between 1 and 3")

    plan.write_text("{", encoding="utf-8")
    rejected(cmd("plan-summary", {"plan-file": str(plan)}), "cannot read search-plan JSON")
    for payload, message in (
        (["not", "an", "object"], "search-plan JSON must be an object"),
        ({"error": {"code": "rate_limited", "message": "wait first"}},
         "Arbiter error rate_limited: wait first"),
        ({}, "search-plan JSON is missing plan"),
        ({"plan": {"search_phrases": []}}, "missing a valid plan.search_phrases array"),
        ({"plan": {"search_phrases": ["ok", " "]}}, "missing a valid plan.search_phrases array"),
        ({"plan": {"search_phrases": ["ok"], "sources": {}}},
         "plan.sources must be an array when present"),
    ):
        write_json(plan, payload)
        rejected(cmd("plan-summary", {"plan-file": str(plan)}), message)

    copy_plan(plan)
    for keep, message in (
        (",,", "keep must contain at least one phrase number"),
        ("1,two", "keep must be a comma-separated list of phrase numbers"),
        ("1,1", "keep must not contain duplicate phrase numbers"),
        ("0", "keep indexes must be between 1 and 3"),
        ("4", "keep indexes must be between 1 and 3"),
    ):
        rejected(cmd("build-finalize", {"plan-file": str(plan), "keep": keep, "out": str(out)}),
                 message)
    write_json(plan, {"plan": {"search_phrases": ["valid"], "entities": {"name": "Acme"}}})
    rejected(cmd("build-finalize", {"plan-file": str(plan), "keep": "1", "out": str(out)}),
             "plan.entities must be an array of strings when present")
    assert not out.exists(), "invalid plans and indexes must not write a finalize body"


def check_plan_options(tmp: Path) -> None:
    """Verify plan-options emits one flat options[] array with stable numbering."""
    plan, out = copy_plan(tmp / "options-plan.json"), tmp / "remove-options.json"
    ok(cmd("plan-options",
           {"mode": "remove", "plan-file": str(plan), "removed": "2", "out": str(out)}),
       f"wrote {out}\n")
    exact_json(out, {
        "mode": "remove",
        "prompt": "Select the search phrases that should be removed.",
        "multi_select": True,
        "option_count": 3,
        "removed_numbers": [2],
        "options": [
            {"label": "1. alpha narrative", "description": "Currently kept; select to remove.",
             "original_number": 1, "phrase": "alpha narrative", "removed": False},
            {"label": '2. beta "quoted" phrase',
             "description": "Already removed; selecting again has no effect.",
             "original_number": 2, "phrase": 'beta "quoted" phrase', "removed": True},
            {"label": "3. gamma \\ path", "description": "Currently kept; select to remove.",
             "original_number": 3, "phrase": "gamma \\ path", "removed": False},
        ],
    })

    # A long plan stays ONE flat list — there is no batching wrapper — and
    # original_number tracks the plan position for every phrase.
    long_plan = tmp / "long-options-plan.json"
    write_json(long_plan, {"plan": {"search_phrases": [f"phrase {n}" for n in range(1, 18)]}})
    ok(cmd("plan-options",
           {"mode": "remove", "plan-file": str(long_plan), "removed": "2 17", "out": str(out)}),
       f"wrote {out}\n")
    long_options = json.loads(out.read_text(encoding="utf-8"))
    assert set(long_options) == {"mode", "prompt", "multi_select", "option_count", "options",
                                "removed_numbers"}, long_options
    assert long_options["option_count"] == 17, long_options
    marks = [(o["original_number"], o["removed"]) for o in long_options["options"]]
    assert marks == [(n, n in (2, 17)) for n in range(1, 18)], marks
    assert long_options["removed_numbers"] == [2, 17], long_options

    suggestions, add_out = tmp / "suggestions.txt", tmp / "add-options.json"
    suggestions.write_text(
        "new suggestion\n\nalpha narrative\nnew suggestion\nphrase, with comma\n",
        encoding="utf-8")
    ok(cmd("plan-options", {"mode": "add", "plan-file": str(plan),
                            "suggestions-file": str(suggestions), "out": str(add_out)}),
       f"wrote {add_out}\n")
    # Duplicates collapse, a phrase already in the plan is filtered out, and a
    # comma inside a phrase survives because selection never parses labels.
    exact_json(add_out, {
        "mode": "add",
        "prompt": ("Select any Spotlight-generated phrases to add. A reviewer may also "
                   "supply their own phrase."),
        "multi_select": True,
        "option_count": 2,
        "source": {"producer": "spotlight_model", "disclosure": DISCLOSURE,
                   "basis": "the available plan summary, categories, and entities"},
        "options": [
            {"label": "new suggestion", "description": DISCLOSURE,
             "suggestion_number": 1, "phrase": "new suggestion"},
            {"label": "phrase, with comma", "description": DISCLOSURE,
             "suggestion_number": 2, "phrase": "phrase, with comma"},
        ],
    })

    bad = tmp / "reject-options.json"
    add_flags = {"mode": "add", "plan-file": str(plan), "out": str(bad)}
    rejected(cmd("plan-options", add_flags), "add mode requires --suggestions-file")
    rejected(cmd("plan-options", {**add_flags, "removed": "1",
                                  "suggestions-file": str(suggestions)}),
             "add mode does not accept --removed")
    rejected(cmd("plan-options", {**add_flags, "mode": "remove",
                                  "suggestions-file": str(suggestions)}),
             "remove mode does not accept --suggestions-file")
    suggestions.write_text("\nalpha narrative\n", encoding="utf-8")
    rejected(cmd("plan-options", {**add_flags, "suggestions-file": str(suggestions)}),
             "suggestions file contains no new phrases")
    for removed, message in (
        ("one", "removed must be a comma-separated list of phrase numbers"),
        ("0", "removed indexes must be between 1 and 3"),
        ("4", "removed indexes must be between 1 and 3"),
        ("2,2", "removed must not contain duplicate phrase numbers"),
    ):
        rejected(cmd("plan-options", {**add_flags, "mode": "remove", "removed": removed}), message)
    assert not bad.exists(), "invalid options input must not write output"


def check_progress(tmp: Path) -> None:
    """Verify per-poll progress rendering, stall detection, and phase handling."""
    progress = tmp / "progress.json"
    shutil.copyfile(FIXTURES / "arbiter-create-progress.json", progress)
    # A fixed clock keeps the reported activity age deterministic.
    ok(cmd("progress-summary",
           {"progress-file": str(progress), "now": "2026-07-25T15:03:00+05:30"}),
       "status=processing | posts=17 | modules=1/3 ready (1 failed) | updated 3m ago\n"
       "  reddit         12 posts  complete - Collected 12 posts\n"
       '  youtube         5 posts  collecting - Fetching page 2 for "fixture phrase"\n'
       "  stage rerank: Reranking 17 posts\n"
       "  analysis: Starting case study analysis.\n"
       "  analysis: Starting analysis for Reddit with 12 posts.\n")
    # A run whose newest activity aged past the threshold must be flagged;
    # otherwise a frozen run reads exactly like a working one.
    stalled = cmd("progress-summary",
                  {"progress-file": str(progress), "now": "2026-07-25T15:52:00+05:30"})
    assert stalled.returncode == 0, stalled.stderr
    assert "no activity for 52m - run may be stalled" in stalled.stdout, stalled.stdout
    fresh = cmd("progress-summary",
                {"progress-file": str(progress), "now": "2026-07-25T15:09:00+05:30"})
    assert "run may be stalled" not in fresh.stdout, "9m stays below the stall threshold"
    rejected(cmd("progress-summary", {"progress-file": str(progress), "now": "not-a-timestamp"}),
             "--now must be an ISO-8601 timestamp")

    # Error envelopes fail; merely incomplete payloads still render a headline.
    for payload, message in (
        (["not", "an", "object"], "progress JSON must be an object"),
        ({"error": {"code": "internal", "message": "request failed"}},
         "Arbiter error internal: request failed"),
    ):
        write_json(progress, payload)
        rejected(cmd("progress-summary", {"progress-file": str(progress)}), message)
    write_json(progress, {"status": "processing", "collection": ["wrong shape"],
                          "analysis": {"modules": "wrong shape"}})
    ok(cmd("progress-summary", {"progress-file": str(progress)}),
       "status=processing | posts=0 | modules=0/0 ready | no activity yet\n")

    # Plan phase: an empty pre-collection payload must not print a platform
    # block that reads as though collection ran and found nothing.
    write_json(progress, {
        "status": "pending",
        "collection": {"total_posts": 0, "platforms": [
            {"platform": "bluesky", "posts": 0, "status": "pending"},
            {"platform": "reddit", "posts": 0, "status": "pending"}]},
        "analysis": {"modules": []},
        "updated_at": "2026-07-25T09:00:00Z",
        "steps": [{"id": "ground", "title": "Web search and grounding", "status": "complete"},
                  {"id": "summary", "title": "Summary and sources", "status": "thinking"}],
    })
    clock = {"progress-file": str(progress), "now": "2026-07-25T09:02:00Z"}
    plan_phase = cmd("progress-summary", {**clock, "phase": "plan"})
    ok(plan_phase,
       "Search plan is still being generated; collection has not started yet. | updated 2m ago\n"
       "  plan: Web search and grounding [complete]\n"
       "  plan: Summary and sources [thinking]\n")
    for misleading in ("status=pending", "posts=0", "bluesky", "reddit"):
        assert misleading not in plan_phase.stdout, plan_phase.stdout
    expected = ("status=pending | posts=0 | modules=0/0 ready | updated 2m ago\n"
                "  bluesky         0 posts  pending\n"
                "  reddit          0 posts  pending\n")
    ok(cmd("progress-summary", {**clock, "phase": "collection"}), expected)
    ok(cmd("progress-summary", clock), expected)

    # Real activity stays visible even when the caller asks for the plan phase.
    for payload in (
        {"status": "failed", "collection": {"total_posts": 0}, "analysis": {"modules": []}},
        {"status": "processing", "collection": {"total_posts": 0}, "analysis": {"modules": []}},
        {"status": "pending", "collection": {"total_posts": 1}, "analysis": {"modules": []}},
        {"status": "pending", "collection": {"total_posts": 0},
         "analysis": {"modules": [{"status": "ready"}]}},
    ):
        write_json(progress, payload)
        active = cmd("progress-summary", {"progress-file": str(progress), "phase": "plan"})
        assert active.returncode == 0, active.stderr
        assert active.stdout.startswith("status="), active.stdout
    invalid = cmd("progress-summary", {"progress-file": str(progress), "phase": "invalid"})
    assert invalid.returncode == 2 and "invalid choice" in invalid.stderr, invalid.stderr


def check_injection(tmp: Path) -> None:
    """Verify metacharacters remain inert and JSON strings round-trip exactly."""
    sentinel = tmp / "INJECTION-RAN"
    query, title, out = tmp / "hq.txt", tmp / "ht.txt", tmp / "hostile-create.json"
    hostile_query = f'$(touch "{sentinel}"); `touch "{sentinel}"`\nquote=" slash=\\'
    hostile_title = f'"; touch "{sentinel}"; # \\'
    query.write_text(hostile_query, encoding="utf-8")
    title.write_text(hostile_title, encoding="utf-8")
    ok(cmd("build-create", create_flags(query, out, title_file=str(title))), f"wrote {out}\n")
    raw = out.read_text(encoding="utf-8")
    body = json.loads(raw)
    assert body["search_query"] == hostile_query, body
    assert body["title"] == hostile_title, body
    assert '\\"' in raw, "quotes must be JSON-escaped"
    assert "\\\\" in raw, "backslashes must be JSON-escaped"
    assert "\\n" in raw, "embedded newlines must be JSON-escaped"
    assert not sentinel.exists(), "query or title text was interpreted by a shell"

    plan, finalize = tmp / "hostile-plan.json", tmp / "hostile-finalize.json"
    phrase = f'$(touch "{sentinel}") && `touch "{sentinel}"` "quoted" \\'
    write_json(plan, {"plan": {
        "summary": phrase, "search_phrases": [phrase], "entities": [],
        "sources": [{"title": phrase, "url": 'https://example.test/?q="x"'}]}})
    additions = tmp / "hostile-phrases.txt"
    additions.write_text(f'; touch "{sentinel}"; #\n', encoding="utf-8")
    ok(cmd("build-finalize", {"plan-file": str(plan), "keep": "1",
                              "phrases-file": str(additions), "out": str(finalize)}),
       f"wrote {finalize}\n")
    phrases = json.loads(finalize.read_text(encoding="utf-8"))["search_phrases"]
    assert phrases == [phrase, f'; touch "{sentinel}"; #'], phrases
    ok(cmd("plan-summary", {"plan-file": str(plan)}),
       f'SUMMARY\n{phrase}\n\nSOURCES\n1. {phrase} - https://example.test/?q="x"\n\n'
       f"SEARCH PHRASES\n 1. {phrase}\n\n1 of 1 phrases kept.\n" + PLAN_FOOT)
    hostile_progress = tmp / "hostile-progress.json"
    write_json(hostile_progress, {"status": phrase, "collection": {}, "analysis": {}})
    ok(cmd("progress-summary", {"progress-file": str(hostile_progress)}),
       f"status={phrase} | posts=0 | modules=0/0 ready | no activity yet\n")
    assert not sentinel.exists(), "plan, phrase, or summary text was shell-evaluated"


def main() -> int:
    """Run the complete offline create-helper regression suite."""
    with tempfile.TemporaryDirectory(prefix="spotlight-arbiter-create-") as tmp_dir:
        tmp = Path(tmp_dir)
        check_create(tmp)
        check_finalize(tmp)
        check_plan_summary(tmp)
        check_plan_options(tmp)
        check_progress(tmp)
        check_injection(tmp)
    print("arbiter create: OK - bodies, validation, review options, and injection verified")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
